# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

def findTheDifference(s, t):
    if s == "":
        return t

    ss = list(s)

    for char in t:
        if char in ss:
            ss.remove(char)
        else:
            return char

#Test cases
s = "abcd"
t = "abcde"
print(findTheDifference(s, t))

s = ""
t = "t"
print(findTheDifference(s, t))

s = "a"
t = "aa"
print(findTheDifference(s, t))

s = "ae"
t = "aea"
print(findTheDifference(s, t))
